.\" $Id$
.\" This file belongs to the public domain.
.Dd July 22, 2004
.Dt PWAIT 1
.Os
.Sh NAME
.Nm pwait
.Nd wait for processes to exit
.Sh SYNOPSIS
.Nm pwait
.Op Fl v
.Ar pid ...
.Sh DESCRIPTION
The
.Nm
utility waits for the given arbitrary processes to exit.
The target processes need not be children of the invoking process.
.Pp
Processes are specified by
.Ar pid
arguments, which are process IDs.
.Pp
The following options are supported:
.Bl -tag -width indent
.It Fl v
When a process exits, display a verbose description containing the exit
status of the exiting process.
.El
.Pp
.Nm
exits zero on success or with one of the
.Xr sysexits 3
error codes on failure.
.Sh EXAMPLES
Show when any process in the system exits (note that
.Nm
will not keep track of new processes that enter the system after it is
executed):
.Pp
.Dl "$ ps -axo pid | tail -n +2 | xargs pwait"
.Sh SEE ALSO
.Xr wait 1
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
