.\" $Id$
.\" This file belongs to the public domain.
.Dd July 21, 2004
.Dt PCRED 1
.Os
.Sh NAME
.Nm pcred
.Nd show process credentials
.Sh SYNOPSIS
.Nm pcred
.Ar pid | core ...
.Sh DESCRIPTION
The
.Nm
utility shows the credentials from the given processes or core files.
Effective, real, and saved user IDs and group IDs, as well as the
group list, are all displayed.
.Pp
Processes are specified with the
.Ar pid
or
.Ar core
arguments, where
.Ar pid
is a process ID and
.Ar core
is the path to a file containing a
.Xr core 5
image of a process.
.Pp
.Nm
exits zero on success or with one of the
.Xr sysexits 3
error codes on failure.
.Sh EXAMPLES
Show the shell's credentials:
.Pp
.Dl $ pcred \&$$
.Pp
Show credentials for all processes in the active system:
.Pp
.Dl "$ ps -axo pid | tail -n +2 | xargs pcred"
.Sh SEE ALSO
.Xr core 5
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
