.\" $Id$
.\" This file belongs to the public domain.
.Dd July 21, 2004
.Dt PCRED 1
.Os
.Sh NAME
.Nm pcred
.Nd show process credentials
.Sh SYNOPSIS
.Nm pcred
.Ar pid ...
.Sh DESCRIPTION
The
.Nm
utility shows the credentials of the given processes.
Effective, real, and saved user IDs and group IDs, as well as the
group list, are all displayed.
Processes are specified by
.Ar pid
arguments, which are process IDs.
.Pp
.Nm
exits zero on success or with one of the
.Xr sysexits 3
error codes on failure.
.Sh EXAMPLES
Show the shell's credentials:
.Pp
.Dl $ pcred \&$$
.Pp
Show credentials of all processes on the system:
.Pp
.Dl "$ ps -axo pid | tail -n +2 | xargs pcred"
.Sh SEE ALSO
.Xr ps 1
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
