.\" $Id$
.\" This file belongs to the public domain.
.Dd July 23, 2004
.Dt PWDX 1
.Os
.Sh NAME
.Nm pwdx
.Nd print process working directories
.Sh SYNOPSIS
.Nm pwdx
.Ar pid ...
.Sh DESCRIPTION
The
.Nm
utility displays the current working directories of the given processes.
Processes are specified by
.Ar pid
arguments, which are process IDs.
.Pp
.Nm
exits zero on success or with one of the
.Xr sysexits 3 
error codes on failure.
.Sh EXAMPLES
Display the current working directory of the shell:
.Pp
.Dl # pwdx $\&$
.Sh SEE ALSO
.Xr pwd 1 ,
.Xr chdir 2 ,
.Xr systrace 4
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
.Sh BUGS
.Nm
uses
.Xr systrace 4
to determine the working directory of the process.
Since
.Nm
must wait for the target process to execute a system call so that
the working directory can be obtained, there may be an indefinite delay
after executing
.Nm
before the working directory will be determined.
Foruntately, the target process must execute a system call to change
its working directory, so the information will nevertheless be accurate.
