.\" $Id$
.\" This file belongs to the public domain.
.Dd July 23, 2004
.Dt PWDX 1
.Os
.Sh NAME
.Nm pwdx
.Nd print current working directories of processes
.Sh SYNOPSIS
.Nm pwdx
.Op Fl F
.Ar pid ...
.Sh DESCRIPTION
The
.Nm
utility displays the current working directories of the given processes.
.Pp
Processes are specified with the
.Ar pid
argument, which is of the form of a process ID or the path to a process
information directory from the
.Pa /proc
process file system (see
.Xr mount_procfs 8 ) .
.Pp
The
.Nm
utility supports the following options:
.Bl -tag -width indent
.It Fl F
Force the retrieval of data.
By default,
.Nm
will wait if another process has a lock on the given process'
information directory until that process relinquishes the lock.
.El
.Pp
The
.Nm
utility exits zero on success or with one of the error codes from
.Xr sysexits 3 
on failure.
.Sh EXAMPLES
Display the current working directories of all processes on the system:
.Pp
.Dl # pwdx /proc/*
.Sh FILES
.Bl -tag -width "/proc/PID" -compact
.It Pa /proc
default mount point for process file system
.It Pa /proc/ Ns Em PID
per-process information directory
.El
.Sh SEE ALSO
.Xr sysexits 3 ,
.Xr putils 7 ,
.Xr mount_procfs 8
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
