.\" $Id$
.\" This file belongs to the public domain.
.Dd July 22, 2004
.Dt PTREE 1
.Os
.Sh NAME
.Nm ptree
.Nd display process trees
.Sh SYNOPSIS
.Nm ptree
.Op Fl a
.Op Ar pid ...
.Sh DESCRIPTION
The
.Nm
utility lists processes in a tree-like format, with child
processes indented from their respective parents.
Processes may specified with the
.Ar pid
argument, which is a process ID.
If no arguments are given, a tree of all processes will be
displayed.
.Pp
The
.Nm
utility supports the following options:
.Bl -tag -width indent
.It Fl a
Trace the tree back to process zero.
By default, the trees for the given processes are rooted from process
one.
With this option, all processes on the system are displayed.
.El
.Pp
The
.Nm
utility exits zero on success or with one of the
.Xr sysexits 3
error codes on failure.
.Sh EXAMPLES
Show the process tree containing the current shell process:
.Pp
.Dl $ ptree \&$$
.Sh SEE ALSO
.Xr ps 1
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
