.\" $Id$
.\" This file belongs to the public domain.
.Dd July 22, 2004
.Dt PUTILS 7
.Os
.Sh NAME
.Nm putils
.Nd process utilities
.Sh SYNOPSIS
.Nm pargs
.Op Fl aceFx
.Op Ar pid Ns | Ns Ar core ...
.Nm pcred
.Op Ar pid Ns | Ns Ar core ...
.Nm pfiles
.Op Fl F
.Ar pid ...
.Nm pflags
.Op Fl r
.Op Ar pid Ns | Ns Ar core ...
.Nm pldd
.Op Fl F
.Op Ar pid Ns | Ns Ar core ...
.Nm plimit
.Op Fl km
.Ar pid ...
.Nm plimit
.Xo
.Oo Fl c
.Ar soft Ns \&, Ns Ar hard Oc
.Oo Fl d
.Ar soft Ns \&, Ns Ar hard Oc
.Oo Fl f
.Ar soft Ns \&, Ns Ar hard Oc
.Oo Fl n
.Ar soft Ns \&, Ns Ar hard Oc
.Oo Fl s
.Ar soft Ns \&, Ns Ar hard Oc
.Oo Fl t
.Ar soft Ns \&, Ns Ar hard Oc
.Oo Fl v
.Ar soft Ns \&, Ns Ar hard Oc
.Xc
.Ar pid ...
.Nm prctl
.Op Fl e | d Ar action
.Op Fl rx
.Xo
.Oo Fl n
.Ar name Op Fl v Ar value Oc
.Xc
.Op Fl i Ar idtype
.Op Ar pid ...
.Nm preap
.Op Fl F
.Ar pid ...
.Nm prun
.Ar pid ...
.Nm psig
.Op Fl n
.Ar pid ...
.Nm pstack
.Op Fl F
.Op Ar pid Ns | Ns Ar core ...
.Nm pstop
.Ar pid ...
.Nm ptime
.Ar command
.Op Ar arguments ...
.Nm ptree
.Op Fl a
.Op Ar pid Ns | Ns Ar core ...
.Nm pwait
.Op Fl v
.Ar pid ...
.Nm pwdx
.Op Ar F
.Ar pid
.Sh DESCRIPTION
.Nm
is collection of utilities for process manipulation, monitoring, and
much more.
Many operate on the
.Pa /proc
file system described in
.Xr mount_procfs 8 .
.Sh FILES
.Bl -tag -width "/proc/curproc" -compact
.It Pa /proc
process filesystem
.It Pa /proc/ Ns Em PID
per-process information directory
.It Pa /proc/curproc
self-referencing process
.El
.Sh SEE ALSO
.Xr pargs 1 ,
.Xr pcred 1 ,
.Xr pfiles 1 ,
.Xr pflags 1 ,
.Xr pgrep 1 ,
.Xr pkill 1 ,
.Xr pldd 1 ,
.Xr plimit 1 ,
.Xr prctl 1 ,
.Xr preap 1 ,
.Xr procmap 1 ,
.Xr prun 1 ,
.Xr psig 1 ,
.Xr pstack 1 ,
.Xr pstop 1 ,
.Xr ptime 1 ,
.Xr ptree 1 ,
.Xr pwait 1 ,
.Xr pwdx 1 ,
.Xr core 5 ,
.Xr mount_procfs 8
.Sh HISTORY
Many
.Nm
were written from scratch based on Sun Solaris 8 & 9 utilities of
similar names.
