.\" $Id$
.\" This file belongs to the public domain.
.Dd July 2, 2004
.Dt PSTACK 1
.Os
.Sh NAME
.Nm pstack
.Nd show process call stack
.Sh SYNOPSIS
.Nm pstack
.Ar pid ...
.Sh DESCRIPTION
The
.Nm
utility
.Pp
The
.Nm
utility supports the following options:
.Bl -tag -width indent
.It Fl
.El
The
.Nm
utility exits zero on success or with one of the
.Xr sysexits 3
error codes on failure.
.Sh EXAMPLES
.Sh SEE ALSO
.Xr procmap 1
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
