.\" $Id$
.\" This file belongs to the public domain.
.Dd July 22, 2004
.Dt PARGS 1
.Os
.Sh NAME
.Nm pargs
.Nd display command lines and arguments of processes
.Sh SYNOPSIS
.Nm pargs
.Op Fl Aace
.Ar pid Ns | Ns Ar core ...
.Sh DESCRIPTION
The
.Nm
utility displays the command lines and arguments and other related data
of the given processes.
.Pp
Processes are specified with the
.Ar pid
and/or
.Ar core
arguments, where
.Ar pid
may be of the form of a process ID or the path to a process information
directory from the
.Pa /proc
process file system (see
.Xr mount_procfs 8 ) ,
or
.Ar core
may be of the form of the path to a file containing a
.Xr core 5
image of a process.
.Pp
The
.Nm
utility supports the following options:
.Bl -tag -width indent
.It Fl A
Display all information available from the given processes, which
currently includes command line and arguments and environment data.
.It Fl a
Display the command line and arguments of the given processes.
This action is the default behavior.
.It Fl c
By default,
.Nm
attempts to change its locale (see
.Xr setlocale 3 )
to that of each process it examines before it displays any data from the
process.
.It Fl e
Display the environment (i.e., the data from
.Xr environ 7 )
of the given processes.
.El
.Pp
The
.Nm
utility exits zero on success or with one of the error codes from
.Xr sysexits 3
on failure.
.Sh FILES
.Bl -tag -width "/proc/PID" -compact
.It Pa /proc
default mount point for process file system
.It Pa /proc/ Ns Em PID
per-process information directory
.El
.Sh EXAMPLES
Display the command lines and arguments of all processes on the system:
.Pp
.Dl $ pargs /proc/*
.Sh SEE ALSO
.Xr setlocale 3 ,
.Xr sysexits 3 ,
.Xr core 5 ,
.Xr environ 7 ,
.Xr putils 7 ,
.Xr mount_procfs 8
.Sh HISTORY
The
.Nm
utility is modeled after the Sun Solaris 8 utility of the same name.
